# Generated by Django 4.0.3 on 2023-01-17 08:05

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Profile Pic')),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='Name')),
                ('age', models.IntegerField(db_index=True, verbose_name='Age')),
                ('designation', models.CharField(db_index=True, max_length=30, verbose_name='Designation')),
                ('hobbies', models.CharField(db_index=True, max_length=200, verbose_name='Hobbies')),
                ('interests', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=100, verbose_name='Interested In')),
                ('drinking', models.CharField(choices=[('daily', 'Daily'), ('ocassionally', 'Ocassionally'), ('teetotaler', 'Teetotaler')], max_length=100, verbose_name='Drinking')),
                ('smoking', models.CharField(choices=[('Daily', 'Daily'), ('Ocassionally', 'Ocassionally'), ('Nonsmoker', 'Non Smoker')], max_length=100, verbose_name='Smoking')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
