# Generated by Django 4.0.3 on 2023-01-17 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=25, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=100, verbose_name='Gender'),
        ),
    ]
